{ pkgs, lib, ... } :


let 
	# E preciso usar o url do ficheiro RAW, nao apenas o link para a pagina html do github desse ficheiro

	# To get the updated hash and automatically substitue it in this file use the replace-hash-nixos command, for example
	# sudo replace-hash-nixos zshrcSource ./zsh/zsh.nix	(provide the marker which is the variable name and the path to this file)
	niriConfigKDL = pkgs.fetchurl { url = "https://raw.githubusercontent.com/Xano-verse/dotfiles/refs/heads/main/niri/config.kdl";
		# Dummy hash to get the expected hash in the error message (under "got:")
		# sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
 		sha256 = "sha256-oiyHVMuFev3miezibhjLQLKSg6o3vL8fEY1DwuExgFc=";	# marker for replace hash script: niriConfigKDL
	};

	#realiseSymlinkScript = pkgs.callPackage ../../scripts-auxiliares/realise-symlink.nix {};

in
{
	# files generated by home-manager cannot be written to because they are just symlinks to the nix store
	# if you want to change the niri config.kdl manually for testing, use the realise-symlink command
	# (.nix script present in this nix config and added to home.packages so it's availble in PATH)
	# delete the changed config.kdl before re-building the system
	# https://kokada.dev/blog/quick-bits-realise-nix-symlinks/


    #programs.niri = {
        #enable = false;			# idk if enable = true creates its own config.kdl that might conflict with mine 
    #};


	# Vai buscar o ficheiro do theme e poe no em ~/.config/niri
	home.file.".config/niri/config.kdl".source = niriConfigKDL;


	# Exemplo de como correr activation script usando um script .nix presente na nix confi
	# chama-se o callPackage como está lá em cima para obter a derivation -> caminho direto pa onde ta o script na nix store
	#home.activation = {
		#myActivationAction = lib.hm.dag.entryAfter ["writeBoundary"] ''
		  #touch $HOME/hello.txt
		  #${realiseSymlinkScript}/bin/realise-symlink $HOME/.zshrc
		  #'';
	#};


}
