{ pkgs, lib, ... } :


let 
	classyTouchSource = pkgs.fetchurl {
		# E preciso usar o url do ficheiro RAW, nao apenas o link para a pagina html do github desse ficheiro
		url = "https://raw.githubusercontent.com/yarisgutierrez/classyTouch_oh-my-zsh/refs/heads/master/classyTouch.zsh-theme";
		# Dummy hash to get the expected hash in the error message (under "got:")
		# sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
		sha256 = "sha256-6V15uzUcCH93IcIq3f3yNvIFO0tNBfn/V2QQ5LmOfDw=";
	};

	zshrcSource = pkgs.fetchurl {
		url = "https://raw.githubusercontent.com/Xano-verse/dotfiles/refs/heads/main/zsh/zshrc-debian.txt";

		#sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
		sha256 = "sha256-dOB8gWQXtzsr3OH1lELv7OhvSHy85+lZT6/0EsPrGjs=";
	};

	#realiseSymlinkScript = pkgs.callPackage ../../scripts-auxiliares/realise-symlink.nix {};

in
{

	programs.zsh = {
		#enable = true;			# enable = true creates a .zshrc, se estou a dar fetch da minha não pôr esta
  		#enableCompletions = true;
  		#autosuggestions.enable = true;
  		syntaxHighlighting.enable = true;

  		shellAliases = {
    			ll = "ls -l";
    			update = "sudo nixos-rebuild switch";
  		};
  		history.size = 10000;
	
		oh-my-zsh = {
    			enable = true;
    			plugins = [ "git" ];
			custom = "/home/nixano/.oh-my-zsh/custom/";
			# Vai procurar na pasta themes pelo specified theme
			theme = "classyTouch";
  		};

	};


	# Vai buscar o ficheiro do theme e poe no em ~/.oh-my-zsh/custom/themes/
	home.file.".oh-my-zsh/custom/themes/classyTouch.zsh-theme".source = classyTouchSource;

	# files generated by home-manager cannot be written to because they are just symlinks to the nix store
	# if you want to change the .zshrc manually for testing, use the realise-symlink command
	# (.nix script present in this nix config and added to home.packages so it's availble in PATH)
	# https://kokada.dev/blog/quick-bits-realise-nix-symlinks/
	home.file.".zshrc" = {
		enable = true;
		source = zshrcSource;
		force = true;		# force replace the .zshrc already present 
	};


	# Exemplo de como correr activation script usando um script .nix presente na nix confi
	# chama-se o callPackage como está lá em cima para obter a derivation -> caminho direto pa onde ta o script na nix store
	#home.activation = {
		#myActivationAction = lib.hm.dag.entryAfter ["writeBoundary"] ''
		  #touch $HOME/hello.txt
		  #${realiseSymlinkScript}/bin/realise-symlink $HOME/.zshrc
		  #'';
	#};


}
