{ pkgs, lib, ... } :


let 
	# E preciso usar o url do ficheiro RAW, nao apenas o link para a pagina html do github desse ficheiro

	# To get the updated hash and automatically substitue it in this file use the replace-hash-nixos command, for example
	# sudo replace-hash-nixos zshrcSource ./zsh/zsh.nix	(provide the marker which is the variable name and the path to this file)
	classyTouchSource = pkgs.fetchurl { url = "https://raw.githubusercontent.com/yarisgutierrez/classyTouch_oh-my-zsh/refs/heads/master/classyTouch.zsh-theme";
		# Dummy hash to get the expected hash in the error message (under "got:")
		# sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
		sha256 = "sha256-6V15uzUcCH93IcIq3f3yNvIFO0tNBfn/V2QQ5LmOfDw="; # marker for replace hash script: classyTouchSource
	};

	zshrcSource = pkgs.fetchurl { url = "https://raw.githubusercontent.com/Xano-verse/dotfiles/refs/heads/main/zsh/zshrc-nixos.txt";

		#sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
 		sha256 = "sha256-2G2sVUw1yrbyc4t59Eiu7Mfk6LVX701JsKeviBu7HQ0=";	# marker for replace hash script: zshrcSource
	};

	#realiseSymlinkScript = pkgs.callPackage ../../scripts-auxiliares/realise-symlink.nix {};

in
{
	# files generated by home-manager cannot be written to because they are just symlinks to the nix store
	# if you want to change the .zshrc manually for testing, use the realise-symlink command
	# (.nix script present in this nix config and added to home.packages so it's availble in PATH)
	# delete the changed .zshrc before re-building the system
	# https://kokada.dev/blog/quick-bits-realise-nix-symlinks/


	programs.zsh = {
		enable = true;			# enable = true creates a .zshrc, se estou a dar fetch da minha não pôr esta
  		syntaxHighlighting.enable = true;

  		shellAliases = {
    			ll = "ls -l";
    			update = "sudo nixos-rebuild switch";
  		};
  		history.size = 10000;
	
		oh-my-zsh = {
    			enable = true;
    			plugins = [ "git" ];
			custom = "/home/xanix/.oh-my-zsh/custom/";
			# Vai procurar na pasta themes pelo specified theme
			theme = "classyTouch";
  		};

		# .zshrc configurations minhas para além do oh-my-zsh (irão ser postas sempre após as configurações do oh-my-zsh)
		initContent = builtins.readFile zshrcSource;
	};


	# Vai buscar o ficheiro do theme e poe no em ~/.oh-my-zsh/custom/themes/
	home.file.".oh-my-zsh/custom/themes/classyTouch.zsh-theme".source = classyTouchSource;


	# Exemplo de como correr activation script usando um script .nix presente na nix confi
	# chama-se o callPackage como está lá em cima para obter a derivation -> caminho direto pa onde ta o script na nix store
	#home.activation = {
		#myActivationAction = lib.hm.dag.entryAfter ["writeBoundary"] ''
		  #touch $HOME/hello.txt
		  #${realiseSymlinkScript}/bin/realise-symlink $HOME/.zshrc
		  #'';
	#};


}
